---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-webservice
  namespace: gitlab
spec:
  secretName: tls-gitlab-webservice
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.spack.io
