version: '3'
services:
  postgres:
    image: postgres:latest
    command: postgres -c log_lock_waits=on -c log_min_duration_statement=100
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: "-Xms250m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
    ports:
      - ${DOCKER_ELASTICSEARCH_PORT-9200}:9200
      - ${DOCKER_ELASTICSEARCH_PORT-9300}:9300

  redis:
    image: redis:latest
    ports:
      - ${DOCKER_REDIS_PORT-6379}:6379
