version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: "-Xms250m -Xmx750m"
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: elastic
    ports:
      - ${DOCKER_OPENSEARCH_PORT-9200}:9200
      - ${DOCKER_OPENSEARCH_PORT-9300}:9300

  redis:
    image: redis:latest
    ports:
      - ${DOCKER_REDIS_PORT-6379}:6379

  prometheus:
    image: prom/prometheus:latest
    ports:
      - ${DOCKER_PROMETHEUS_PORT-9090}:9090

  gitlab-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - gitlab-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab

volumes:
  postgres:
  gitlab-db:
