---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-sentry
  namespace: sentry
spec:
  secretName: tls-sentry
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: sentry.spack.io
  dnsNames:
  - sentry.spack.io
