---
apiVersion: v1
kind: Service
metadata:
  name: gantry-spack-io
  namespace: spack
  labels:
    app: gantry-spack-io
    svc: web
spec:
  selector:
    app: gantry-spack-io
    svc: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
