---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../production/sentry/namespace.yaml
  - ../../production/sentry/certificates.yaml
  - ../../production/sentry/release.yaml

patches:
  - target:
      kind: Certificate
      name: tls-sentry
      namespace: sentry
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: sentry.staging.spack.io

  - target:
      kind: Certificate
      name: tls-sentry
      namespace: sentry
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: sentry.staging.spack.io

      - op: replace
        path: /spec/commonName
        value: sentry.staging.spack.io

  - target:
      kind: HelmRelease
      name: sentry
      namespace: sentry
    patch: |-
      - op: replace
        path: /spec/values/ingress/hostname
        value: sentry.staging.spack.io

      - op: replace
        path: /spec/values/ingress/tls/0/hosts
        value: [sentry.staging.spack.io]
