---
apiVersion: v1
kind: Service
metadata:
  name: build-timing-processor
  namespace: custom
  labels:
    app: build-timing-processor
    svc: web
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: build-timing-processor
    svc: web
