---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-binary-caches
  namespace: custom
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: index-binary-caches
          restartPolicy: Never
          containers:
          - name: index-binary-caches
            image: ghcr.io/spack/cache-indexer:0.0.2
            imagePullPolicy: IfNotPresent
            env:
              - name: BUCKET_NAME
                valueFrom:
                  configMapKeyRef:
                    name: cache-indexer-config
                    key: bucket_name
          nodeSelector:
            spack.io/node-pool: base
