---
# Provisioner for gitlab pods
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: gitlab
spec:
  providerRef:
    name: default

  # Terminate nodes after 5 minutes of idle time
  ttlSecondsAfterEmpty: 300

  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.xlarge", "m5.xlarge"]

    # Always use on-demand
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]

  # Only provision nodes for pods specifying the gitlab node pool
  labels:
    spack.io/node-pool: gitlab
