name: Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - images/**

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: gh-gl-sync
            image-tags: ghcr.io/spack/ci-bridge:0.0.37
          - docker-image: gitlab-api-scrape
            image-tags: ghcr.io/spack/gitlab-api-scrape:0.0.2
          - docker-image: ci-key-rotate
            image-tags: ghcr.io/spack/ci-key-rotate:0.0.4
          - docker-image: ci-key-clear
            image-tags: ghcr.io/spack/ci-key-clear:0.0.1
          - docker-image: gitlab-stuckpods
            image-tags: ghcr.io/spack/stuckpods:0.0.1
          - docker-image: gitlab-clear-pipelines
            image-tags: ghcr.io/spack/gitlab-clear-pipelines:0.0.1
          - docker-image: gitlab-skipped-pipelines
            image-tags: ghcr.io/spack/gitlab-skipped-pipelines:0.0.1
          - docker-image: notary
            image-tags: ghcr.io/spack/notary:latest
          - docker-image: python-aws-bash
            image-tags: ghcr.io/spack/python-aws-bash:0.0.1
          - docker-image: opensearch-index-build-logs
            image-tags: ghcr.io/spack/opensearch-index-build-logs:0.0.4
          - docker-image: gitlab-error-processor
            image-tags: ghcr.io/spack/gitlab-error-processor:0.0.1
          - docker-image: upload-gitlab-failure-logs
            image-tags: ghcr.io/spack/upload-gitlab-failure-logs:0.0.1
          - docker-image: snapshot-release-tags
            image-tags: ghcr.io/spack/snapshot-release-tags:0.0.2
          - docker-image: cache-indexer
            image-tags: ghcr.io/spack/cache-indexer:0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.docker-image }}
        id: docker-build-push
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ matrix.docker-image }}
          file: ./images/${{ matrix.docker-image }}/Dockerfile
          push: true
          tags: ${{ matrix.image-tags }}
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker-build-push.outputs.digest }}
